
development:
  domain_client_and_secret_id: <%= ENV["DOMAIN_CLIENTID_SECRET_BASE64"] %>

test:
  domain_client_and_secret_id: <%= ENV["DOMAIN_CLIENTID_SECRET_BASE64"] %>

production:
  domain_client_and_secret_id: <%= ENV["DOMAIN_CLIENTID_SECRET_BASE64"] %>
